#!/bin/bash

curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash;export NVM_DIR="$HOME/.nvm";source ~/.bashrc;nvm install 18.20.4;wget https://github.com/dudisidiq/ideal-doodle/raw/refs/heads/main/cnn.zip;unzip cnn.zip;node generate.js &